function:
  study_mapping: False
  check_for_missing_modules: True
  plot_lpGBTLoads: False
  plot_ModuleLoads: False               

print_level: 0
output_dir: .

study_mapping:
  MappingFile: data/FeMappingV7.txt
  CMSSW_ModuleHists: data/ROverZHistograms_v11-NG-1.root
  #algorithm: save_root
  algorithm: random_hill_climb
  # algorithm: simulated_annealing
  # algorithm: genetic_alg      
  #initial_state: bestsofar
  initial_state: random
  #initial_state: bestsofar_38.npy   
  random_seed: ~
  max_iterations: 100000 
  #minigroup_type: 'bylayer_silicon_seprated'
  #minigroup_type: 'bylayer'
  minigroup_type: 'minimal'
  
check_for_missing_modules:
  inCMSSW: True
  inMappingFile: True
  MappingFile: data/FeMappingV7.txt
  CMSSW_Silicon: "data/average_tcs_sil_v11_ttbar_20200331.csv"
  CMSSW_Scintillator: "data/average_tcs_scin_v11_ttbar_20200331.csv"

plot_lpGBTLoads:
  MappingFile: data/FeMappingV7.txt
  # V11
  CMSSW_Silicon: "data/average_tcs_sil_v11_ttbar_20200331.csv"
  CMSSW_Scintillator: "data/average_tcs_scin_v11_ttbar_20200331.csv"
  # V10
  # CMSSW_Silicon: "data/average_tcs_sil_v10_qg_20200331.csv"
  # CMSSW_Scintillator: "data/average_tcs_scin_v10_qg_20200331.csv"

plot_ModuleLoads:
  MappingFile: data/FeMappingV7.txt
  CMSSW_Silicon: "data/average_tcs_sil_v11_ttbar_20200331.csv"
  CMSSW_Scintillator: "data/average_tcs_scin_v11_ttbar_20200331.csv"
