function:
  checkFluctuations: True
  plot_MeanMax: False
  plot_Truncation: False

print_level: 0
#output_dir: plots/fluctuation_ttbar
output_dir: plots/fluctuation_nugun

checkFluctuations:
  initial_state: bundles_job_fluctuation_studies.npy
  # cmsswNtuple: data/small_v11_neutrino_gun_200611.root
  cmsswNtuple: data/small_v11_relval_ttbar_2006011.root
  mappingFile: data/FeMappingV7.txt

plot_MeanMax:
  eventData: alldata_ttbar_3530.txt
  #eventData: alldata_2500.txt

plot_Truncation:
  #eventData: alldata_ttbar_3530.txt
  eventData: alldata_2500.txt