function:
  checkFluctuations: True
  plot_MeanMax: False
  plot_Truncation: False

print_level: 0
#output_dir: plots/20200623/fluctuation_nugun
output_dir: plots/20200623/fluctuation_ttbar

checkFluctuations:
  initial_state: bundles_job_best_neutrinogun_200617.npy
  #cmsswNtuple: data/small_v11_relval_neutrino_gun_200611.root
  cmsswNtuple: data/small_v11_relval_ttbar_200611.root
  #outputName: alldata_ttbar_2006022.txt
  outputName: tempdata.txt
  #outputName: alldata_neutrino_gun_2006022.txt
  mappingFile: data/FeMappingV7.txt

plot_MeanMax:
  #eventData: data/alldata_neutrinogun_2006022.txt
  eventData: data/alldata_ttbar_2006011.txt
  includePhi60: True
  
plot_Truncation:
  #eventData: data/alldata_neutrinogun_2006022.txt
  eventData: data/alldata_ttbar_2006011.txt
  includePhi60: True