function:
  checkFluctuations: False
  plot_MeanMax: False
  plot_Truncation: True

print_level: 0
output_dir: .

checkFluctuations:
  initial_state: bundles_job_fluctuation_studies.npy
  cmsswNtuple: data/small_v11_neutrino_gun_200415.root
  mappingFile: data/FeMappingV7.txt

plot_MeanMax:
  eventData: alldata_2500.txt

plot_Truncation:
  eventData: alldata_2500.txt